import type { EditorPreset } from "..";
import { extensiveExtensions } from "./extensions";
import { ExtensiveEditor } from "./ExtensiveEditor";
import { createPresetEditorConfig } from "../../core/preset-config";

export const extensivePreset: EditorPreset = {
  id: "extensive",
  label: "Extensive",
  description: "All features enabled for power users.",
  extensions: [...extensiveExtensions],
  components: {
    Editor: ExtensiveEditor,
  },
  toolbar: [
    "undo",
    "redo",
    "heading",
    "fontFamily",
    "fontSize",
    "lineHeight",
    "textColor",
    "textHighlight",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "subscript",
    "superscript",
    "link",
    "image",
    "table",
    "horizontalRule",
    "htmlEmbed",
    "iframeEmbed",
    "youtubeEmbed",
    "blockquote",
    "code",
    "codeBlock",
    "bulletedList",
    "numberedList",
    "checkList",
    "commandPalette",
    "floatingToolbar",
    "contextMenu",
    "draggableBlock",
    "customNode",
    "sourceMode",
    "themeToggle",
  ],
  config: createPresetEditorConfig("extensive", "Write anything..."),
  css: "extensive/styles.css",
};
