import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/presets/extensive/index.ts",
    "src/presets/compose/index.ts",
    "src/presets/simple-editor/index.ts",
    "src/presets/legacy-rich/index.ts",
    "src/presets/md-editor/index.ts",
    "src/presets/html-editor/index.ts",
    "src/presets/slash-editor/index.ts",
    "src/presets/headless-editor/index.ts",
  ],
  format: ["esm"],
  dts: true,
  clean: true,
  minify: true,
  sourcemap: false,
  external: [
    "react",
    "react-dom",
    "@lyfie/luthor-headless",
    "lexical",
    "@lexical/code",
    "@lexical/link",
    "@lexical/list",
    "@lexical/markdown",
    "@lexical/react",
    "@lexical/rich-text",
    "@lexical/selection",
    "@lexical/table",
    "@lexical/utils",
  ],
  splitting: true,
  treeshake: true,
  target: "es2020",
});
