import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/presets/extensive/index.ts",
    "src/presets/simple-text/index.ts",
    "src/presets/rich-text-box/index.ts",
    "src/presets/chat-window/index.ts",
    "src/presets/email-compose/index.ts",
    "src/presets/md-text/index.ts",
    "src/presets/notion-like/index.ts",
    "src/presets/headless-editor/index.ts",
    "src/presets/notes/index.ts",
  ],
  format: ["esm"],
  dts: true,
  clean: true,
  minify: true,
  sourcemap: false,
  external: [
    "react",
    "react-dom",
    "@lyfie/luthor-headless",
    "lexical",
    "@lexical/code",
    "@lexical/link",
    "@lexical/list",
    "@lexical/markdown",
    "@lexical/react",
    "@lexical/rich-text",
    "@lexical/selection",
    "@lexical/table",
    "@lexical/utils",
  ],
  splitting: true,
  treeshake: true,
  target: "es2020",
});
